class ExperimentNotFound(Exception):
    pass

class ExperimentConflict(Exception):
    pass 